name: pytorch
channels: 
 - pytorch
 - anaconda 
 - conda-forge
dependencies:
 - python=3.6.7
 - pytorch
 - torchvision
 - cudatoolkit=10.0
 - matplotlib
 - ipykernel
 - h5py
 - pandas
 - xarray
 - dask
 - bottleneck
 - cartopy
 - statsmodels
 - scikit-learn
